config:
  giturl: https://github.training.cerner.com/ob095866/Test1.git
  gitUsername: ob095866
  gitPassword: Umadevi@1506
  gitcloneDirectoryPath: C:\\Cloning2
spring:
  application:
    name: gittool
    
  
  
    
    